apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "b7bc2b46-88f0-4aca-9278-e30cafc93a41"
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - image: mcr.microsoft.com/azure-cli:latest
    name: oidc
    command:
    - /bin/bash
    - -c
    - --
    args:
    - while true; do sleep 30; done;
  nodeSelector:
    kubernetes.io/os: linux