apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: acr-oci
  namespace: cluster-config
spec:
  interval: "30m"
  type: oci
  url: oci://acrakstoredemo23c3e0.azurecr.io/helm

