apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: cluster-config
spec:
  targetNamespace: redis
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: acr-oci
        namespace: cluster-config
      version: "23.0.4"
  interval: 2m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
